#!/bin/bash

if test "$(echo "14.1 13.1" | tr " " "n" | sort -rV | head -n 1)" == "14.1"; then
	echo "version node mayor que la requerida"
else
	echo "hola"
fi

#if "$(node --version)" -ge '14'; then
#	echo "Vamos a instalar node"
#else
#	echo "node está en la versión correcta"
#fi

